replicas: 2

logLevel: debug
clusterName: "dev-eks_cluster"
clusterEndpoint: "https://7090A25779526A4E9F16A6932AD35B82.gr7.eu-central-1.eks.amazonaws.com"
aws:
  defaultInstanceProfile: "dev-KarpenterControllerProfile"

serviceAccount:
  create: true
  annotations:
    "eks.amazonaws.com/role-arn" : "arn:aws:iam::698471419283:role/dev-KarpenterControllerRole"

revisionHistoryLimit: 10
strategy:
  rollingUpdate:
    maxUnavailable: 1

controller:
  resources:
    requests:
      cpu: 1
      memory: 1Gi
    limits:
      cpu: 1
      memory: 1Gi