apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: toxicity-gateway
  namespace: dev
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - toxicity.dev.curieo.ai
    port:
      name: http
      number: 80
      protocol: HTTP
