---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ .Release.Name }}-admin-gateway
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - {{ .Release.Name }}-admin.{{ .Values.domain_name }}
      port:
        name: https
        number: 443
        protocol: HTTP