apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: {{ include "text-generation-inference.fullname" . }}
  labels:
    {{- include "text-generation-inference.labels" . | nindent 4 }}
  annotations:
    prometheus.kserve.io/port: '8082'
    prometheus.kserve.io/path: "/metrics"
    serving.kserve.io/enable-prometheus-scraping: "true"
spec:
  predictor:
    {{- if not .Values.autoscaling.enabled }}
    minReplicas: 1
    maxReplicas: 1
    scaleMetric: concurrency
    {{- end }}
    containers:
      - name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 12 }}
        readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 12 }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        env:
          {{- with .Values.env }}
          {{ toYaml . | nindent 12 }}
          {{- end }}
          - name: HUGGING_FACE_HUB_TOKEN
            value: "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"
        args:
        - --model-id
        - {{ .Values.model | quote }}
        {{- if .Values.revision }}
        - --revision
        - {{ .Values.revision | quote }}
        {{- end }}
        {{- if .Values.dtype }}
        - --dtype
        - {{ .Values.dtype | quote }}
        {{- end }}
        {{- if .Values.json_output }}
        - --json-output
        {{- end }}
        {{ /*
        {{- if .Values.resources }}
          {{- if index .Values.resources.limits "nvidia.com/gpu" }}
          - name: NUM_SHARD
            value: {{ index .Values.resources.limits "nvidia.com/gpu" | quote }}
          {{- end }}
        {{- end }}
        - name: PORT
          value: {{ .Values.port | quote }}
        {{- if .Values.quantize }}
        - name: QUANTIZE
          value: {{ .Values.quantize | quote }}
        {{- end }}
        */}}
        {{- with .Values.volumeMounts }}
        volumeMounts:
          {{- toYaml . | nindent 12 }}
        {{- end }}
    {{- with .Values.volumes }}
    volumes:
      {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.nodeSelector }}
    nodeSelector:
      {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
    affinity:
      {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
    tolerations:
      {{- toYaml . | nindent 8 }}
    {{- end }}
