apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./base

patchesStrategicMerge:
  - dex-configmap-patch.yaml
  - jupyter-web-app-patch.yaml
  - config-domain-patch.yaml
  - kserve-models-web-app-config-patch.yaml
  - allowlist-by-paths-transformer-authpolicy.yaml
  - allowlist-by-paths-predit-authpolicy.yaml
