apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: text-generation
  annotations:
    prometheus.kserve.io/port: '8082'
    prometheus.kserve.io/path: "/metrics"
    serving.kserve.io/enable-prometheus-scraping: "true"
spec:
  predictor:
    minReplicas: 0
    maxReplicas: 1
    scaleMetric: concurrency
    containers:
      - name: text-generation-container
        image: ghcr.io/huggingface/text-generation-inference:2.0
        args:
        - --model-id
        - microsoft/Phi-3-medium-4k-instruct
        - --revision
        - refs/pr/68 # <-- https://huggingface.co/microsoft/Phi-3-mini-128k-instruct/discussions/68
        - --trust-remote-code
        - --dtype
        - float16
        - --json-output
        - --api-key
        - 6c32eb73-76a2-4c31-9e28-41dd416bd1d4
        resources:
          limits:
            nvidia.com/gpu: 1
            cpu: 2
            memory:  6Gi 
          requests:
            nvidia.com/gpu: 1
            cpu: 1
            memory:  4Gi 
