apiVersion: apps/v1 # Updated API version
kind: Deployment
metadata:
  name: vegeta
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vegeta
  template:
    metadata:
      labels:
        app: vegeta
    spec:
      containers:
      - name: vegeta
        image: peterevans/vegeta:latest-vegeta12.8.4
        command: ["/bin/sh", "-ec", "sleep 1000"]
