apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qdrant-efs-claim
  namespace: qdrant
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 500Gi
