apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: openbiollm
  namespace: dev
  annotations:
    prometheus.kserve.io/port: '8082'
    prometheus.kserve.io/path: "/metrics"
    serving.kserve.io/enable-prometheus-scraping: "true"
spec:
  predictor:
    tolerations:
      - key: type
        operator: "Equal"
        value: "large-gpu-workloads"
        effect: "NoSchedule"
    minReplicas: 1
    maxReplicas: 1
    scaleMetric: concurrency
    volumes:
      - name: model-storage
        persistentVolumeClaim:
          claimName: hf-cache-pv-claim
    containers:
      - name: text-generation-container
        image: ghcr.io/huggingface/text-generation-inference:2.0
        env:
          - name: HUGGING_FACE_HUB_TOKEN
            value: "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"
        args:
        - --model-id
        - ivarflakstad/Llama3-OpenBioLLM-8B
        - --dtype
        - bfloat16
        - --json-output
        - --port
        - "80"
        - --huggingface-hub-cache
        - "/usr/src/data"
        volumeMounts:
          - name: model-storage
            mountPath: /usr/src/data
        resources:
          limits:
            nvidia.com/gpu: 1
            cpu: 4
            memory:  32Gi
          requests:
            nvidia.com/gpu: 1
            cpu: 1
            memory:  8Gi
